version: '3.9'

services:

  mysql:
    image: mysql:8
    container_name: cloudy-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cloudy
      - MYSQL_DATABASE=cloudy1234!
    ports:
      - "3306:3306" # MySQL 기본 포트를 외부에 노출
    volumes:
      - db:/var/lib/mysql # MySQL 데이터를 영구적으로 저장
    networks:
      - cloudy
    restart: "always"

  cloudy-be:
    image: cloudy-be:latest
    container_name: cloudy-be
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    restart: "always"
    networks:
      - cloudy

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx:/etc/nginx  # nginx 설정 파일 경로
      - /var/www/html:/var/www/html  # 정적 파일 제공을 위한 경로
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서 경로
    depends_on:
      - cloudy-be
    restart: "always"
    networks:
      - cloudy

volumes:
  db: {}

networks:
  cloudy:
    name: cloudy
    driver: bridge
